[profile.default]
src = "src"
out = "out"
optimizer = true
via_ir = true
libs = ["lib"]
fs_permissions = [
  { access = "read", path = "./addresses" },
  { access = "read", path = "./chainConfigs" },
  { access = "read", path = "./package.json" },
  { access = "readwrite", path = "./deterministicConfig" },
]
allow_paths = ["node_modules/@zoralabs/protocol-rewards"]

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "${BASE_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
